USE movie_review;

-- Seed data for dbProj_categories
ALTER TABLE dbProj_categories AUTO_INCREMENT = 1;
INSERT IGNORE INTO dbProj_categories (category_id, name) VALUES ('3', 'Action');
INSERT IGNORE INTO dbProj_categories (category_id, name) VALUES ('10', 'Adventure');
INSERT IGNORE INTO dbProj_categories (category_id, name) VALUES ('29', 'Animation');
INSERT IGNORE INTO dbProj_categories (category_id, name) VALUES ('16', 'Comedy');
INSERT IGNORE INTO dbProj_categories (category_id, name) VALUES ('4', 'Crime');
INSERT IGNORE INTO dbProj_categories (category_id, name) VALUES ('7', 'Drama');
INSERT IGNORE INTO dbProj_categories (category_id, name) VALUES ('1', 'Horror');
INSERT IGNORE INTO dbProj_categories (category_id, name) VALUES ('12', 'Romance');
INSERT IGNORE INTO dbProj_categories (category_id, name) VALUES ('6', 'Sci-Fi');
INSERT IGNORE INTO dbProj_categories (category_id, name) VALUES ('19', 'Thriller');

-- Seed data for dbProj_movies
ALTER TABLE dbProj_movies AUTO_INCREMENT = 1;
INSERT IGNORE INTO dbProj_movies (movie_id, title, tmdb_id, short_description, synopsis, release_year, duration_min, image_url, media_url, download_url, fanart_bg, fanart_logo, color_tl, color_tr, color_br, color_bl, created_by, is_published, published_at, view_count, avg_rating, rating_count, created_at, updated_at) VALUES ('21', 'Swapped', '1007757', 'A small woodland creature and a majestic bird, two natural sworn enemies of the Valley, magically trade places and set off on an adventure of a lifetime to switch back. Their journey soon uncovers a greater threat—one that could endanger not only their species, but the entire valley they call home.', 'A small woodland creature and a majestic bird, two natural sworn enemies of the Valley, magically trade places and set off on an adventure of a lifetime to switch back. Their journey soon uncovers a greater threat—one that could endanger not only their species, but the entire valley they call home.', '2026', NULL, 'assets/posters/1007757.jpg', NULL, NULL, 'assets/fanart/backgrounds/1007757.jpg', 'assets/fanart/logos/1007757.png', '162313', '351506', '1e2d2c', '4d3c29', NULL, '1', '2026-06-02 18:28:39', '0', '8.97', '0', '2026-06-02 18:28:39', '2026-06-02 18:28:39');
INSERT IGNORE INTO dbProj_movies (movie_id, title, tmdb_id, short_description, synopsis, release_year, duration_min, image_url, media_url, download_url, fanart_bg, fanart_logo, color_tl, color_tr, color_br, color_bl, created_by, is_published, published_at, view_count, avg_rating, rating_count, created_at, updated_at) VALUES ('22', 'The Shawshank Redemption', '278', 'Imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.', 'Imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.', '1994', NULL, 'assets/posters/278.jpg', NULL, NULL, 'assets/fanart/backgrounds/278.jpg', 'assets/fanart/logos/278.png', '21211f', '563b29', '4c3f38', '47403f', NULL, '1', '2026-06-02 18:28:44', '0', '8.72', '0', '2026-06-02 18:28:44', '2026-06-02 18:28:44');
INSERT IGNORE INTO dbProj_movies (movie_id, title, tmdb_id, short_description, synopsis, release_year, duration_min, image_url, media_url, download_url, fanart_bg, fanart_logo, color_tl, color_tr, color_br, color_bl, created_by, is_published, published_at, view_count, avg_rating, rating_count, created_at, updated_at) VALUES ('23', 'The Godfather', '238', 'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.', 'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.', '1972', NULL, 'assets/posters/238.jpg', NULL, NULL, 'assets/fanart/backgrounds/238.jpg', 'assets/fanart/logos/238.png', '0b0b0b', '660507', '660507', '2f2f2f', NULL, '1', '2026-06-02 18:28:48', '0', '8.70', '0', '2026-06-02 18:28:48', '2026-06-02 18:28:48');
INSERT IGNORE INTO dbProj_movies (movie_id, title, tmdb_id, short_description, synopsis, release_year, duration_min, image_url, media_url, download_url, fanart_bg, fanart_logo, color_tl, color_tr, color_br, color_bl, created_by, is_published, published_at, view_count, avg_rating, rating_count, created_at, updated_at) VALUES ('24', 'Project Hail Mary', '687163', 'Science teacher Ryland Grace wakes up on a spaceship light years from home with no recollection of who he is or how he got there. As his memory returns, he begins to uncover his mission: solve the riddle of the mysterious substance causing the sun to die out. He must call on his scientific knowledge and unorthodox ideas to save everything on Earth from extinction.', 'Science teacher Ryland Grace wakes up on a spaceship light years from home with no recollection of who he is or how he got there. As his memory returns, he begins to uncover his mission: solve the riddle of the mysterious substance causing the sun to die out. He must call on his scientific knowledge and unorthodox ideas to save everything on Earth from extinction.', '2026', NULL, 'assets/posters/687163.jpg', NULL, NULL, 'assets/fanart/backgrounds/687163.jpg', 'assets/fanart/logos/687163.png', '111f0c', '17240f', '27372b', '1d1007', NULL, '1', '2026-06-02 18:28:54', '0', '8.65', '0', '2026-06-02 18:28:54', '2026-06-02 18:28:54');
INSERT IGNORE INTO dbProj_movies (movie_id, title, tmdb_id, short_description, synopsis, release_year, duration_min, image_url, media_url, download_url, fanart_bg, fanart_logo, color_tl, color_tr, color_br, color_bl, created_by, is_published, published_at, view_count, avg_rating, rating_count, created_at, updated_at) VALUES ('25', 'The Godfather Part II', '240', 'In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.', 'In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.', '1974', NULL, 'assets/posters/240.jpg', NULL, NULL, 'assets/fanart/backgrounds/240.jpg', 'assets/fanart/logos/240.png', '17090c', '0c1313', '14121b', '180908', NULL, '1', '2026-06-02 18:28:58', '0', '8.57', '0', '2026-06-02 18:28:58', '2026-06-02 18:28:58');
INSERT IGNORE INTO dbProj_movies (movie_id, title, tmdb_id, short_description, synopsis, release_year, duration_min, image_url, media_url, download_url, fanart_bg, fanart_logo, color_tl, color_tr, color_br, color_bl, created_by, is_published, published_at, view_count, avg_rating, rating_count, created_at, updated_at) VALUES ('26', 'Schindler\'s List', '424', 'The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.', 'The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.', '1993', NULL, 'assets/posters/424.jpg', NULL, NULL, 'assets/fanart/backgrounds/424.jpg', 'assets/fanart/logos/424.png', '0b0b0b', '131313', '131313', '030303', NULL, '1', '2026-06-02 18:29:03', '0', '8.57', '0', '2026-06-02 18:29:03', '2026-06-02 18:29:03');
INSERT IGNORE INTO dbProj_movies (movie_id, title, tmdb_id, short_description, synopsis, release_year, duration_min, image_url, media_url, download_url, fanart_bg, fanart_logo, color_tl, color_tr, color_br, color_bl, created_by, is_published, published_at, view_count, avg_rating, rating_count, created_at, updated_at) VALUES ('27', '12 Angry Men', '389', 'The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors\' prejudices and preconceptions about the trial, the accused, and each other.', 'The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors\' prejudices and preconceptions about the trial, the accused, and each other.', '1957', NULL, 'assets/posters/389.jpg', NULL, NULL, 'assets/fanart/backgrounds/389.jpg', 'assets/fanart/logos/389.png', '360300', '660803', '660f04', '65170f', NULL, '1', '2026-06-02 18:29:12', '0', '8.56', '0', '2026-06-02 18:29:12', '2026-06-02 18:29:12');
INSERT IGNORE INTO dbProj_movies (movie_id, title, tmdb_id, short_description, synopsis, release_year, duration_min, image_url, media_url, download_url, fanart_bg, fanart_logo, color_tl, color_tr, color_br, color_bl, created_by, is_published, published_at, view_count, avg_rating, rating_count, created_at, updated_at) VALUES ('28', 'Remarkably Bright Creatures', '1330021', 'Through unlikely bonds formed during night shifts at a local aquarium, Tova, an elderly widow, learns of a life-changing discovery that may bring her joy and wonder once again.', 'Through unlikely bonds formed during night shifts at a local aquarium, Tova, an elderly widow, learns of a life-changing discovery that may bring her joy and wonder once again.', '2026', NULL, 'assets/posters/1330021.jpg', NULL, NULL, 'assets/fanart/backgrounds/1330021.jpg', 'assets/fanart/logos/1330021.png', '122f2e', '474d40', '231b12', '324645', NULL, '1', '2026-06-02 18:29:14', '0', '8.55', '0', '2026-06-02 18:29:14', '2026-06-02 18:29:14');
INSERT IGNORE INTO dbProj_movies (movie_id, title, tmdb_id, short_description, synopsis, release_year, duration_min, image_url, media_url, download_url, fanart_bg, fanart_logo, color_tl, color_tr, color_br, color_bl, created_by, is_published, published_at, view_count, avg_rating, rating_count, created_at, updated_at) VALUES ('29', 'Spirited Away', '129', 'A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.', 'A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.', '2001', NULL, 'assets/posters/129.jpg', NULL, NULL, 'assets/fanart/backgrounds/129.jpg', 'assets/fanart/logos/129.png', '012432', '604932', '0a2746', '053b55', NULL, '1', '2026-06-02 18:29:18', '0', '8.54', '0', '2026-06-02 18:29:18', '2026-06-02 18:29:18');
INSERT IGNORE INTO dbProj_movies (movie_id, title, tmdb_id, short_description, synopsis, release_year, duration_min, image_url, media_url, download_url, fanart_bg, fanart_logo, color_tl, color_tr, color_br, color_bl, created_by, is_published, published_at, view_count, avg_rating, rating_count, created_at, updated_at) VALUES ('30', 'The Dark Knight', '155', 'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.', 'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.', '2008', NULL, 'assets/posters/155.jpg', NULL, NULL, 'assets/fanart/backgrounds/155.jpg', 'assets/fanart/logos/155.png', '132132', '371e29', '3d4056', '1c475f', NULL, '1', '2026-06-02 18:29:23', '0', '8.53', '0', '2026-06-02 18:29:23', '2026-06-02 18:29:23');
INSERT IGNORE INTO dbProj_movies (movie_id, title, tmdb_id, short_description, synopsis, release_year, duration_min, image_url, media_url, download_url, fanart_bg, fanart_logo, color_tl, color_tr, color_br, color_bl, created_by, is_published, published_at, view_count, avg_rating, rating_count, created_at, updated_at) VALUES ('31', 'Dilwale Dulhania Le Jayenge', '19404', 'Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.', 'Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.', '1995', NULL, 'assets/posters/19404.jpg', NULL, NULL, 'assets/fanart/backgrounds/19404.jpg', 'assets/fanart/logos/19404.png', '2a171a', '492d33', '462521', '27171a', NULL, '1', '2026-06-02 18:29:29', '0', '8.51', '0', '2026-06-02 18:29:29', '2026-06-02 18:29:29');
INSERT IGNORE INTO dbProj_movies (movie_id, title, tmdb_id, short_description, synopsis, release_year, duration_min, image_url, media_url, download_url, fanart_bg, fanart_logo, color_tl, color_tr, color_br, color_bl, created_by, is_published, published_at, view_count, avg_rating, rating_count, created_at, updated_at) VALUES ('32', 'The Green Mile', '497', 'A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people\'s ailments. When the cell block\'s head guard, Paul Edgecomb, recognizes Coffey\'s miraculous gift, he tries desperately to help stave off the condemned man\'s execution.', 'A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people\'s ailments. When the cell block\'s head guard, Paul Edgecomb, recognizes Coffey\'s miraculous gift, he tries desperately to help stave off the condemned man\'s execution.', '1999', NULL, 'assets/posters/497.jpg', NULL, NULL, 'assets/fanart/backgrounds/497.jpg', 'assets/fanart/logos/497.png', '1c1206', '39240c', '0c0403', '0c130b', NULL, '1', '2026-06-02 18:29:33', '0', '8.51', '0', '2026-06-02 18:29:33', '2026-06-02 18:29:33');
INSERT IGNORE INTO dbProj_movies (movie_id, title, tmdb_id, short_description, synopsis, release_year, duration_min, image_url, media_url, download_url, fanart_bg, fanart_logo, color_tl, color_tr, color_br, color_bl, created_by, is_published, published_at, view_count, avg_rating, rating_count, created_at, updated_at) VALUES ('33', '¿Quieres ser mi hijo?', '1181678', 'Lu, a conformist woman in her forties, learns that her 15-year partner has been having extramarital affairs. Starting from scratch, she gets involved in an unexpected relationship with a young womanizer.', 'Lu, a conformist woman in her forties, learns that her 15-year partner has been having extramarital affairs. Starting from scratch, she gets involved in an unexpected relationship with a young womanizer.', '2023', NULL, 'assets/posters/1181678.jpg', NULL, NULL, 'assets/fanart/backgrounds/1181678.jpg', 'assets/fanart/logos/1181678.png', '1f1913', '35221c', '2f353a', '212320', NULL, '1', '2026-06-02 18:29:35', '0', '8.49', '0', '2026-06-02 18:29:35', '2026-06-02 18:29:35');
INSERT IGNORE INTO dbProj_movies (movie_id, title, tmdb_id, short_description, synopsis, release_year, duration_min, image_url, media_url, download_url, fanart_bg, fanart_logo, color_tl, color_tr, color_br, color_bl, created_by, is_published, published_at, view_count, avg_rating, rating_count, created_at, updated_at) VALUES ('34', 'The Lord of the Rings: The Return of the King', '122', 'As armies mass for a final battle that will decide the fate of the world--and powerful, ancient forces of Light and Dark compete to determine the outcome--one member of the Fellowship of the Ring is revealed as the noble heir to the throne of the Kings of Men. Yet, the sole hope for triumph over evil lies with a brave hobbit, Frodo, who, accompanied by his loyal friend Sam and the hideous, wretched Gollum, ventures deep into the very dark heart of Mordor on his seemingly impossible quest to dest', 'As armies mass for a final battle that will decide the fate of the world--and powerful, ancient forces of Light and Dark compete to determine the outcome--one member of the Fellowship of the Ring is revealed as the noble heir to the throne of the Kings of Men. Yet, the sole hope for triumph over evil lies with a brave hobbit, Frodo, who, accompanied by his loyal friend Sam and the hideous, wretched Gollum, ventures deep into the very dark heart of Mordor on his seemingly impossible quest to destroy the Ring of Power.​', '2003', NULL, 'assets/posters/122.jpg', NULL, NULL, 'assets/fanart/backgrounds/122.jpg', 'assets/fanart/logos/122.png', '25170f', '352116', '180c0a', '2b231c', NULL, '1', '2026-06-02 18:29:41', '0', '8.50', '0', '2026-06-02 18:29:41', '2026-06-02 18:29:41');
INSERT IGNORE INTO dbProj_movies (movie_id, title, tmdb_id, short_description, synopsis, release_year, duration_min, image_url, media_url, download_url, fanart_bg, fanart_logo, color_tl, color_tr, color_br, color_bl, created_by, is_published, published_at, view_count, avg_rating, rating_count, created_at, updated_at) VALUES ('35', 'Parasite', '496243', 'All unemployed, Ki-taek\'s family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.', 'All unemployed, Ki-taek\'s family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.', '2019', NULL, 'assets/posters/496243.jpg', NULL, NULL, 'assets/fanart/backgrounds/496243.jpg', 'assets/fanart/logos/496243.png', '111b24', '1a4a50', '1d3e48', '0f2822', NULL, '1', '2026-06-02 18:29:46', '0', '8.50', '0', '2026-06-02 18:29:46', '2026-06-02 18:29:46');
INSERT IGNORE INTO dbProj_movies (movie_id, title, tmdb_id, short_description, synopsis, release_year, duration_min, image_url, media_url, download_url, fanart_bg, fanart_logo, color_tl, color_tr, color_br, color_bl, created_by, is_published, published_at, view_count, avg_rating, rating_count, created_at, updated_at) VALUES ('36', 'Pulp Fiction', '680', 'A burger-loving hit man, his philosophical partner, a drug-addled gangster\'s moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.', 'A burger-loving hit man, his philosophical partner, a drug-addled gangster\'s moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.', '1994', NULL, 'assets/posters/680.jpg', NULL, NULL, 'assets/fanart/backgrounds/680.jpg', 'assets/fanart/logos/680.png', '301f1e', '22324c', '2b1c1b', '1a242b', NULL, '1', '2026-06-02 18:29:52', '0', '8.48', '0', '2026-06-02 18:29:52', '2026-06-02 18:29:52');
INSERT IGNORE INTO dbProj_movies (movie_id, title, tmdb_id, short_description, synopsis, release_year, duration_min, image_url, media_url, download_url, fanart_bg, fanart_logo, color_tl, color_tr, color_br, color_bl, created_by, is_published, published_at, view_count, avg_rating, rating_count, created_at, updated_at) VALUES ('37', 'Your Name.', '372058', 'High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.', 'High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.', '2016', NULL, 'assets/posters/372058.jpg', NULL, NULL, 'assets/fanart/backgrounds/372058.jpg', 'assets/fanart/logos/372058.png', '012134', '613c33', '054064', '623232', NULL, '1', '2026-06-02 18:29:57', '0', '8.48', '0', '2026-06-02 18:29:57', '2026-06-02 18:29:57');
INSERT IGNORE INTO dbProj_movies (movie_id, title, tmdb_id, short_description, synopsis, release_year, duration_min, image_url, media_url, download_url, fanart_bg, fanart_logo, color_tl, color_tr, color_br, color_bl, created_by, is_published, published_at, view_count, avg_rating, rating_count, created_at, updated_at) VALUES ('38', 'Interstellar', '157336', 'The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.', 'The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.', '2014', NULL, 'assets/posters/157336.jpg', NULL, NULL, 'assets/fanart/backgrounds/157336.jpg', 'assets/fanart/logos/157336.png', '23292f', '0e202c', '1f2d28', '2a2125', NULL, '1', '2026-06-02 18:30:02', '0', '8.48', '0', '2026-06-02 18:30:02', '2026-06-02 18:30:02');
INSERT IGNORE INTO dbProj_movies (movie_id, title, tmdb_id, short_description, synopsis, release_year, duration_min, image_url, media_url, download_url, fanart_bg, fanart_logo, color_tl, color_tr, color_br, color_bl, created_by, is_published, published_at, view_count, avg_rating, rating_count, created_at, updated_at) VALUES ('39', 'The Good, the Bad and the Ugly', '429', 'While the Civil War rages on between the Union and the Confederacy, three men – a quiet loner, a ruthless hitman, and a Mexican bandit – comb the American Southwest in search of a strongbox containing $200,000 in stolen gold.', 'While the Civil War rages on between the Union and the Confederacy, three men – a quiet loner, a ruthless hitman, and a Mexican bandit – comb the American Southwest in search of a strongbox containing $200,000 in stolen gold.', '1966', NULL, 'assets/posters/429.jpg', NULL, NULL, 'assets/fanart/backgrounds/429.jpg', 'assets/fanart/logos/429.png', '27160c', '251810', '170f0d', '170f0c', NULL, '1', '2026-06-02 18:30:07', '0', '8.47', '0', '2026-06-02 18:30:07', '2026-06-02 18:30:07');
INSERT IGNORE INTO dbProj_movies (movie_id, title, tmdb_id, short_description, synopsis, release_year, duration_min, image_url, media_url, download_url, fanart_bg, fanart_logo, color_tl, color_tr, color_br, color_bl, created_by, is_published, published_at, view_count, avg_rating, rating_count, created_at, updated_at) VALUES ('40', 'Forrest Gump', '13', 'A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do. But despite all he has achieved, his one true love eludes him.', 'A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do. But despite all he has achieved, his one true love eludes him.', '1994', NULL, 'assets/posters/13.jpg', NULL, NULL, 'assets/fanart/backgrounds/13.jpg', 'assets/fanart/logos/13.png', '311b19', '1b1414', '312220', '2a1c1a', NULL, '1', '2026-06-02 18:30:12', '0', '8.47', '0', '2026-06-02 18:30:12', '2026-06-02 18:30:12');

-- Seed data for dbProj_movie_categories
ALTER TABLE dbProj_movie_categories AUTO_INCREMENT = 1;
INSERT IGNORE INTO dbProj_movie_categories (movie_id, category_id) VALUES ('21', '10');
INSERT IGNORE INTO dbProj_movie_categories (movie_id, category_id) VALUES ('22', '7');
INSERT IGNORE INTO dbProj_movie_categories (movie_id, category_id) VALUES ('23', '7');
INSERT IGNORE INTO dbProj_movie_categories (movie_id, category_id) VALUES ('24', '6');
INSERT IGNORE INTO dbProj_movie_categories (movie_id, category_id) VALUES ('25', '7');
INSERT IGNORE INTO dbProj_movie_categories (movie_id, category_id) VALUES ('26', '7');
INSERT IGNORE INTO dbProj_movie_categories (movie_id, category_id) VALUES ('27', '7');
INSERT IGNORE INTO dbProj_movie_categories (movie_id, category_id) VALUES ('28', '7');
INSERT IGNORE INTO dbProj_movie_categories (movie_id, category_id) VALUES ('29', '29');
INSERT IGNORE INTO dbProj_movie_categories (movie_id, category_id) VALUES ('30', '3');
INSERT IGNORE INTO dbProj_movie_categories (movie_id, category_id) VALUES ('31', '16');
INSERT IGNORE INTO dbProj_movie_categories (movie_id, category_id) VALUES ('32', '7');
INSERT IGNORE INTO dbProj_movie_categories (movie_id, category_id) VALUES ('33', '16');
INSERT IGNORE INTO dbProj_movie_categories (movie_id, category_id) VALUES ('34', '10');
INSERT IGNORE INTO dbProj_movie_categories (movie_id, category_id) VALUES ('35', '16');
INSERT IGNORE INTO dbProj_movie_categories (movie_id, category_id) VALUES ('36', '19');
INSERT IGNORE INTO dbProj_movie_categories (movie_id, category_id) VALUES ('37', '29');
INSERT IGNORE INTO dbProj_movie_categories (movie_id, category_id) VALUES ('38', '10');
INSERT IGNORE INTO dbProj_movie_categories (movie_id, category_id) VALUES ('39', '7');
INSERT IGNORE INTO dbProj_movie_categories (movie_id, category_id) VALUES ('40', '16');

